### ISSUE TITLE
uses-sdk:minSdkVersion 7 cannot be smaller than version 9

### ISSUE THREAD

**Issue by Rudloff** [marcoM32/SeaMapDroid#3]
Hello,

I'm getting this error when building:
```
> Manifest merger failed : uses-sdk:minSdkVersion 7 cannot be smaller than version 9 declared in library [com.android.support:design:25.3.1] /home/pierre/www/SeaMapDroid/app/build/intermediates/exploded-aar/com.android.support/design/25.3.1/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="android.support.design" to force usage
```

If I can understand correctly, you are targetting SDK 7 but `com.android.support:design` requires SDK 9.

(This also affects F-Droid releases.)

**Comment by marcoM32** [comment]
Hi @Rudloff,
do you have an idea on how to solve this problem?

**Comment by mimi89999** [comment]
@marcoM32 Could you also change the `v1.4.2` tag to 8141db8ef7a0dda238d9324f92e39391277c92da ?

**Comment by marcoM32** [comment]
Hi @mimi89999, I have released a new version that includes this fix

**Comment by mimi89999** [comment]
@marcoM32 Thanks. It built fine. I updated the metadata file: https://gitlab.com/fdroid/fdroiddata/commit/f1bd2021b3f9d7b432d76c5cd1b35a3c058d173b
