### ISSUE TITLE
Propose new logo

### ISSUE THREAD

**Issue by anaufalm** [marcoM32/SeaMapDroid#4]
Hello, I want to contribute to this awesome project, and I have a new logo design for you, if you allowed I will send to you :)

**Comment by marcoM32** [comment]
Hi @anaufalm,
your contribution would be great !!
Can you make the necessary changes and put them in a new pull request?

Thank you

**Comment by naufaldsg** [comment]
Hi @marcoM32 , this is me @anaufalm, I just want to inform you that I lost my account few weeks ago, so sad and I use this account for now, thank you. And I really really sorry for responding to your message now, I was very busy last month with my studies. And now I can focus on contributing.

About your logo, can we start it again? I will make it for you asap.

**Comment by marcoM32** [comment]
Hi @anaufalm, I would really happy if you make a new icon for this application. Do you already have any idea for the realization?

**Comment by naufaldsg** [comment]
What about this?

I personally highly recommend using the B logo, because it is very representative of SeaMapDroid visuals and the logo is very modern and minimalist. What do you think?

![seamap01](https://user-images.githubusercontent.com/44208945/47922593-02790800-deea-11e8-8b1d-13bea2fbe61d.png)

**Comment by marcoM32** [comment]
The B icon it's really beautiful, thanks alot for your work. I will integrate it in the next relase.

**Comment by naufaldsg** [comment]
Ur welcome, what about the color? Do you like it? I think combinations blue is good which is the sea also identic with blue color.

**Comment by naufaldsg** [comment]
I've fork your repo and [add the logo](https://github.com/naufaal/SeaMapDroid/commit/ea3499f45750c7d02dc9b0189e191cc6fdaf98f5) and [update readme](https://github.com/naufaal/SeaMapDroid/commit/bc2b56988cb33c563451a7604d738f4ec0522a59) file. Can you merge it?

**Comment by marcoM32** [comment]
Yes, I think it will be very good, otherwise we will change the main color of the app.
I do not see any pull requests, could you send me one with your changes?

First, however, could you rename the "Logo" folder in "logo"?

**Comment by naufaldsg** [comment]
Yaa, but I cant upload logo file to your repo, its need push access to this repository. So I upload to fork repo and create [pull request](https://github.com/marcoM32/SeaMapDroid/pull/10).

Sorry, I am bad with coding and not use Git on my desktop, I just open it with my browser. So, could you rename it? Thank you 😆

**Comment by marcoM32** [comment]
No problem, in the next days I copy the changes from your's repo in my source. 
I'll let you know when your changes will be integrated.

**Comment by naufaldsg** [comment]
I have create pull request, would you check it?

**Comment by marcoM32** [comment]
I accepted your request, the changes will be present in the new version scheduled soon.
Thank you @naufaldsg
